accelerate launch sdxl_train.py \
    --image_dir './datasets/dataset' \
    --metadata_file './datasets/metadata.json' \
    --pretrained_model_name_or_path './models/sdxl.safetensors' \
    --vae './models/sdxl_vae.safetensors' \
    --logging_dir './logs' \
    --recording_dir './datasets/records' \
    --tokenizer_cache_dir './tokenizers' \
    --mixed_precision 'bf16' \
    --save_precision 'bf16' \
    --full_bf16 \
    --optimizer_type 'AdaFactor' \
    --gradient_checkpointing \
    --gradient_accumulation_steps 48 \
    --num_train_epochs 100 \
    --batch_size 1 \
    --learning_rate 7.5e-6 \
    --train_text_encoder \
    --learning_rate_te1 3.75e-6 \
    --learning_rate_te2 3.75e-6 \
    --lr_scheduler constant_with_warmup \
    --lr_warmup_steps 500 \
    --save_every_n_epochs 1 \
    --save_every_n_steps 500 \
    --save_on_train_end \
    --save_on_keyboard_interrupt \
    --sample_every_n_epochs 1 \
    --sample_every_n_steps 500 \
    --sample_prompts './benchmarks/example_benchmark.json' \
    --sample_sampler 'euler_a' \
    --xformers \
    --vae_batch_size 4 \
    --flip_aug \
    --cache_latents \
    --cache_latents_to_disk \
    --keep_cached_latents_in_memory \
    --max_token_length 225 \
    --max_dataset_n_workers 40
    